#
# This file contains configuration flags for the site
#

# Name of your site (displayed in the header)
title: The RMIT Programming Club

# Site Tagline (displayed in the header)
tagline: Code. Connect. Contribute.

# Site Description 
description: Offical Website for RMIT Programming Club.

# Your website URL 
# url: http://rmitprogramming.club 

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Banner Text
bannertext: "Meetings Time/Day TBC (RMIT Sutherland Lab ~ 14.11.38)"

# Favicon
favicon: /images/favicon.png

# Site Logo
sitelogo: /images/site-logo.png

# Footer Logo
footerlogo: /images/footerlogo.png

# Social Links
github_username: rmit-programming-club
fb_username: rmitprogramming.club
email: programming.club@rmit.edu.au

# Nav Bar Links (Add new or change pages if your site requires it)
blog: "/" 
projects: "/projects"
membership: "https://rusu.rmit.edu.au/Clubs/programming"
contact: "/contact"
about: "/about"
sponsors: "/sponsors"
store: "https://www.redbubble.com/people/rmitprogramming/shop"
resources: "/resoureces"

# !! You don't need to change any of the configuration flags below !!

# Pagenate support
paginate: 5
paginate_path: "/page:num/"

permalink: /:title/

# This will require each of these plugins automatically.
plugins:
  - jekyll-paginate 

# Build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  meetings:
    output: true
